### ISSUE TITLE
关于http_config.h文件的处理，以及install选项的问题

### ISSUE THREAD

**Issue by tccxy** [jiejieTop/http-client#9]
@jiejieTop 

哈喽，我在一个小的嵌入式程序中使用了本项目，感觉对嵌入式小项目很友好，e。。之前使用libcurl，感觉到的是我们这个项目在响应速度上要比libcurl慢，，也可能是我配置的问题，在我们的小程序中，以动态库的形式使用了本项目作为程序的一部分，说下自己的建议

1.http_config.h感觉应该作为一个单独的配置目录而存在，不应放在test目录中，因为他影响的是整个工程而不是单独的上层测试代码，，针对响应慢的问题，我修改了http_config.h的HTTP_DEFAULT_CMD_TIMEOUT 参数，感觉响应的速度已经满足我们的要求了

2.cmake的install参数似乎并没有设置吗？？？，我这边如果在工程中使用，，,在一个脚本中用了如下的方法。。。
```
cp ${HTTP_CLIENT_UNPACK}/platform/linux ${HTTP_CLIENT_INSTALL}/include -Rdf
cp ${HTTP_CLIENT_UNPACK}/test/http_config.h ${HTTP_CLIENT_INSTALL}/include -Rdf
cp ${HTTP_CLIENT_UNPACK}/common ${HTTP_CLIENT_INSTALL}/include -Rdf
cp ${HTTP_CLIENT_UNPACK}/common/log ${HTTP_CLIENT_INSTALL}/include -Rdf
cp ${HTTP_CLIENT_UNPACK}/network/mbedtls/include ${HTTP_CLIENT_INSTALL}/include -Rdf
cp ${HTTP_CLIENT_UNPACK}/network ${HTTP_CLIENT_INSTALL}/include -Rdf
cp ${HTTP_CLIENT_UNPACK}/libhttp ${HTTP_CLIENT_INSTALL}/include -Rdf
cp ${HTTP_CLIENT_UNPACK}/httpclient ${HTTP_CLIENT_INSTALL}/include -Rdf
cp lib ${PREFIX} -Rdf
```

3.似乎还有些log级别的设置，，即使设置warn level 但是代码中还是有很多的printf，不知是否刻意而为之？？

以上，如果需要修改？？我可以测试后pr？？

**Comment by jiejieTop** [comment]
hello，你好呀，这个库是我之前写的，主要是嵌入式上所以，现在由于不在业内，就基本没有怎么维护，还是有问题的，您这边按您的要求该即可，可以提交pr



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月19日(周一) 上午8:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [jiejieTop/http-client] 关于http_config.h文件的处理，以及install选项的问题 (#9)




 
@jiejieTop
 
哈喽，我在一个小的嵌入式程序中使用了本项目，感觉对嵌入式小项目很友好，e。。之前使用libcurl，感觉到的是我们这个项目在响应速度上要比libcurl慢，，也可能是我配置的问题，在我们的小程序中，以动态库的形式使用了本项目作为程序的一部分，说下自己的建议
 
1.http_config.h感觉应该作为一个单独的配置目录而存在，不应放在test目录中，因为他影响的是整个工程而不是单独的上层测试代码，，针对响应慢的问题，我修改了http_config.h的HTTP_DEFAULT_CMD_TIMEOUT 参数，感觉响应的速度已经满足我们的要求了
 
2.cmake的install参数似乎并没有设置吗？？？，我这边如果在工程中使用，，,在一个脚本中用了如下的方法。。。
 cp ${HTTP_CLIENT_UNPACK}/platform/linux ${HTTP_CLIENT_INSTALL}/include -Rdf cp ${HTTP_CLIENT_UNPACK}/test/http_config.h ${HTTP_CLIENT_INSTALL}/include -Rdf cp ${HTTP_CLIENT_UNPACK}/common ${HTTP_CLIENT_INSTALL}/include -Rdf cp ${HTTP_CLIENT_UNPACK}/common/log ${HTTP_CLIENT_INSTALL}/include -Rdf cp ${HTTP_CLIENT_UNPACK}/network/mbedtls/include ${HTTP_CLIENT_INSTALL}/include -Rdf cp ${HTTP_CLIENT_UNPACK}/network ${HTTP_CLIENT_INSTALL}/include -Rdf cp ${HTTP_CLIENT_UNPACK}/libhttp ${HTTP_CLIENT_INSTALL}/include -Rdf cp ${HTTP_CLIENT_UNPACK}/httpclient ${HTTP_CLIENT_INSTALL}/include -Rdf cp lib ${PREFIX} -Rdf  
3.似乎还有些log级别的设置，，即使设置warn level 但是代码中还是有很多的printf，不知是否刻意而为之？？
 
以上，如果需要修改？？我可以测试后pr？？
